#!/bin/sh

brave-browser \
	--enable-gpu-rasterization \
	--no-default-browser-check \
	--disable-pings \
	--renderer-process-limit=999 \
	--ignore-gpu-blacklist \
	--enable-features=VaapiVideoDecoder \
	"$@"
