#!/usr/bin/env bash
#
# # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918433
# export MESA_GLSL_CACHE_DISABLE=true
# # UPDATE: was supposed to fix this error, but didn't:
# # sandbox_linux.cc(374)] : InitializeSandbox() called with multiple threads in process gpu-process.
# # it means the gpu process isn't sandboxed

browser=brave-browser

# in case we forgot and left it paused; harmless if running
presume $browser

declare -A profiles=(
	personal Default
	work "Profile 1"
)

profile=personal
[[ $1 == '-w' ]] && { profile=work; shift; }
[[ $1 == '-p' ]] && shift # default

args=(
	$browser
	--new-window
	--profile-directory="${profiles[$profile]}"
	--enable-gpu-rasterization
	--no-default-browser-check
	--disable-pings
	--renderer-process-limit=999
	--ignore-gpu-blacklist

	# for testing, but not confirmed these actually do anything yet
	#--enable-logging=stderr
	#--v=1
	#--v=2

	# do not use libsecret even if org.freedesktop.secrets provider is
	# available on dbus, which it would be if gnome-keyring or keepassxc
	# was in use, see task def2ba8c, this may be something we want to do
	# later, but right now we force the basic
	# TODO: test restart to verify this doesn't wipe our passwords, after
	# saving our passwords
	#
	--password-store=basic

	# todo: eventually we want to use vulkan, but this is a project for
	# later and may be superseded by wayland if xwayland is good enough
	# while we transition to qtile
	#
	#--enable-accelerated-video-decode
	#--enable-features=VaapiVideoDecoder
	#--enable-vulkan

	"$@"
)
setsid ${args[*]} </dev/null & disown
