#!/usr/bin/env bash
#
# # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918433
# export MESA_GLSL_CACHE_DISABLE=true
# # UPDATE: was supposed to fix this error, but didn't:
# # sandbox_linux.cc(374)] : InitializeSandbox() called with multiple threads in process gpu-process.
# # it means the gpu process isn't sandboxed

browser=brave-browser

# in case we forgot and left it paused; harmless if running
presume $browser

args=(
	$browser
	--new-window
	--enable-gpu-rasterization
	--no-default-browser-check
	--disable-pings
	--renderer-process-limit=999
	--ignore-gpu-blacklist
	#--enable-accelerated-video-decode
	#--enable-features=VaapiVideoDecoder
	#--enable-vulkan
	"$@"
)
setsid ${args[*]} </dev/null & disown
