#!/usr/bin/env bash

xset m 2 16
xset r rate 265 85

#
# "xinput --list" -> "xinput --list-props 11"
# "ls /dev/input/by-path/*event-mouse" -> "sudo evtest /dev/input/event1"
# left, right, top, bottom; X varies from X1 to X2; Y varies from Y1 to Y2
#

ps2base='DLL096D:01 06CB:CDE6'

touchpad="$ps2base Touchpad"
#mouse="$ps2base Mouse"
mouse="PixArt HP USB Optical Mouse"

setprop () { xinput --set-prop "$1" "$2" "$3" || true; }

setprop "$touchpad" 'libinput Tapping Enabled' 1
setprop "$touchpad" 'libinput Tapping Drag Enabled' 1
setprop "$touchpad" 'libinput Natural Scrolling Enabled' 1
setprop "$touchpad" 'libinput Disable While Typing Enabled' 1
setprop "$touchpad" 'libinput Middle Emulation Enabled' 1
setprop "$touchpad" 'libinput Horizontal Scroll Enabled' 1
setprop "$touchpad" 'libinput Accel Speed' 1.0

setprop "$mouse" 'libinput Natural Scrolling Enabled' 1
setprop "$mouse" 'libinput Horizontal Scroll Enabled' 1
setprop "$mouse" 'libinput Accel Speed' 1.0

xkeymap=~/.Xkeymap
xkbcomp -I$(dirname $(readlink -f $xkeymap))/xkb $xkeymap :0 2>/dev/null
