#!/usr/bin/env bash

xset m 2 16
xset r rate 265 85

#
# "xinput --list" -> "xinput --list-props 11"
# "ls /dev/input/by-path/*event-mouse" -> "sudo evtest /dev/input/event1"
#
setprop () { xinput --set-prop "$@" || true; }

xkeymap=~/.Xkeymap
xkbcomp -I$(dirname $(readlink -f $xkeymap))/xkb $xkeymap :0 2>/dev/null
